---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

Prompt: Growth as a data scientist: Describe how you have improved as a practitioner and student of data science this quarter through your work in the course. Focus specifically on data science concepts and the skills we employed in learning them. Don't just give a laundry list of topics that you learned (those are in the syllabus, so we know them already). Focus instead on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth. Explain in this essay how this artifact shows growth in the way you are describing.

As a data scientist I have grown throughout this class, especially with problem solving. A common struggle I have with programming is that I get stuck on a problem and do not know how to continue from there. I think in this class I had to confront that struggle many times and learn how to figure out what to do from there. For example, using other resources like Google, putting a ? and then the function name in the console so I could get the help file to pop up, and breaking up my code chunk by chunk to learn what each line of my code is doing. I think this has helped me grow as a data scientist because programming languages are constantly changing with new packages being added and updated and learning how to incorporate these updates is an important skill. An example of this is the across() function's format being changed while we were in Stat 331 this quarter and I needed to go back through my old code to update this. This is shown in challenge 3. Another example where I think I grew as a data scientist in terms of become a better problem solver was in Lab 8 Step 2: Creating Sentences(Practice Act Part of Lab 8). This function that I was creating had a couple different parts to it and I think I used my resources like the ? in the console, lectures, and posit cloud stringr resource very well which added my growth with problem solving.

I think another topic that I have showed growth throughout the quarter is through my data visualizations. At the beginning of the quarter the visualizations I was making were very basic. For example, in lab 3 question 10 I created a very basic box plot where I just changed the color of the box plot. In the last challenge I did, challenge 9 (included in my portoflio), I created a couple visualizations where I changed the color of the graphs, used facet wrap, added a regression line, and changing the color of the title and axis labels. I think this shows growth because I am learning more about the ggplot package and being able to change colors of specific items and other factors makes my visualizations more clear.

The last example of my growth in data science is reducing the number of unnecessary data sets I make. At the beginning of the quarter each time I needed to make a new visualization or table with a variation of the original data set I would make a new data set with these values. As the quarter has progressed I have learned how to be more picky with what data sets I want to save as a new data set and not create extra data sets that are unnecessary. For example, in challenge 9 question 9 I realized that I did not need to make a whole new data set for allens, alan, or allan just to filter the data by the year 2000 and states California and Pennsylvanian. Instead I could just filter the data set I already have, get the table I wanted, and then move on to the next question without creating an extra data set.
