---
title: "The Power of Efficiency"
format: html
editor: visual
---

Prompt: The power of efficiency: As we've said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term "efficiency" means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Include: What is the definition of "efficiency"? What does efficiency look like in statistical computing / data science? What does efficiency allow you to do? Why is efficiency important? Where did you encounter efficiency, and what were some "a-ha" moments you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

Efficiency is having the least amount of waste possible, for example taking more time than necessary, or using more product than necessary would not be efficient. Efficiency is also ever changing because as new technology comes out there are new ways to make things more efficient.

Efficiency in a statistical computing / data science way looks like trying to make your code as simple as possible. For data scientists making your code as efficient as possible is extremely important because when you are working with huge sets of data, 100,000s of lines, it will take noticeably longer if your code has more lines and functions then necessary. This means that as a data scientist it is important to prioritize efficiency because if your code is taking a long time to run that will be a major barrier to being able to quickly change parts of your code in the future. When you use more functions than necessary you are creating a waste of time and energy to run and also write the code. Instead, if you can avoid unnecessary computations this will allow you to get the results you want but in a quick fashion. I think a good word to describe code efficiency is pithy, you want your code to be effective but concise.

Efficiency allows you to allocate your time and money well and use it to in other areas. Being able to do things in a quick way means you have more of both these resources that can be used in other areas that are just as important.

Efficiency is important because why would you want to do something a longer way when you can do it in a shorter way. For example, if I was able to mutate and summarize a data set in 4 lines instead of 10, I would first of all be able to type those lines out way quicker and second of all the computer would take less time running through that code. While the difference between 4 and 10 lines does not make a noticeable different to us now imagine that number multiplied by 1000 or 10,000, then it would make a huge difference. This is why efficiency is important.

I encountered efficiency the most in this class when I had to summarize or mutate across rows, or mutate two or more columns. The across() function is very influential for efficiency because it allows me to do the same function across all the columns I specify. An a-ha moment I had was when I realized that I could use the mutate() function once but mutate multiple columns by just separating each by a comma. This is shown in Lab 4 question 7 because I realized instead of typing out the mutate() function twice and taking the time to do that I could just use it once which makes my code more efficient. Although this seems like an obvious efficient change to make to my code after almost completing this course, in the moment I felt like I was getting a better understanding of efficiency and what it means while coding. Another a-ha moment I had about efficiency is how important the across() function is to R. This function allows the same action to be applied to all or a select number of columns. This can turn multiple lines of code into 1 line. This is included in my portfolio in challenge 3 where I used the across() function to find the mean of 10 different columns. This was an a-ha moment for me because I realized that if there was no across() function in R I would have to have written 10 lines of code right there.
